# Generated by Django 4.2.7 on 2024-05-23 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WAEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('total_questions', models.IntegerField(default=50, editable=False)),
            ],
            options={
                'verbose_name': 'WAEC Exam',
                'verbose_name_plural': 'WAEC Exams',
            },
        ),
        migrations.CreateModel(
            name='SUBJECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='exams.waec')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='QUESTIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(max_length=500)),
                ('option_A', models.CharField(max_length=500)),
                ('option_B', models.CharField(max_length=500)),
                ('option_C', models.CharField(max_length=500)),
                ('option_D', models.CharField(max_length=500)),
                ('option_E', models.CharField(max_length=500)),
                ('answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('E', 'Option E')], max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exams.subject')),
            ],
            options={
                'verbose_name': 'WAEC Question',
                'verbose_name_plural': 'WAEC Questions',
            },
        ),
    ]
