# Generated by Django 4.2.7 on 2023-12-31 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_exam_uploaded_at_exam_uploader_alter_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='uploader',
        ),
        migrations.AddField(
            model_name='question',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
