# Generated by Django 4.2.7 on 2023-12-31 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_remove_exam_uploaded_at_remove_exam_uploader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, default=exams.models.get_default_subject, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
