# Generated by Django 4.2.7 on 2024-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_questions_year'),
    ]

    operations = [
    ]
