# Generated by Django 5.0 on 2024-01-01 09:28

import django.db.models.deletion
import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='exams.exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, default=exams.models.get_default_topic, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.topic'),
        ),
    ]
