# Generated by Django 5.0 on 2024-01-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_exam_duration_remove_exam_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
    ]
