# Generated by Django 4.2.7 on 2024-05-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_questions_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waec',
            name='total_questions',
            field=models.IntegerField(default=3, editable=False),
        ),
    ]
