# Generated by Django 4.2.7 on 2024-05-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_alter_questions_subject_alter_questions_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exams.year'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='exams.waec'),
        ),
    ]
