# Generated by Django 4.2.7 on 2024-05-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_alter_waec_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('E', 'Option E')], max_length=1, null=True),
        ),
    ]
