# Generated by Django 4.2.7 on 2024-06-02 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_alter_questions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waec',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
