# Generated by Django 4.2.15 on 2024-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_subject_name_alter_topic_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningcontentsection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='additional_resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='core_concepts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='examples',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='interactive_elements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='learning_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='practice_problems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='reflection_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='step_by_step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontentsection',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='learningcontentsection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='learningcontentsection',
            name='section_type',
        ),
    ]
