# Generated by Django 4.2.15 on 2024-09-02 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0007_learningcontentsection_dynamic_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateLearningContentContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=2)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('learning_objectives', models.JSONField(blank=True, default=dict)),
                ('dynamic_content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_content_containers', to='ai.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_content_containers', to='ai.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_content_containers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LearningContentSection',
        ),
    ]
