# Generated by Django 4.2.15 on 2024-09-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
