# Generated by Django 4.2.15 on 2024-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_testinstance_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatelearningcontentcontainer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
