# Generated by Django 4.2.7 on 2024-05-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_questions_year'),
        ('quiz_manager', '0002_testinstance_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinstance',
            name='year',
        ),
        migrations.AddField(
            model_name='testinstance',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exams.year'),
            preserve_default=False,
        ),
    ]
