# Generated by Django 4.2.7 on 2024-05-24 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_waec_total_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_manager', '0003_remove_testinstance_year_testinstance_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinstance',
            name='subjects',
        ),
        migrations.AddField(
            model_name='testinstance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exams.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
