# Generated by Django 4.2.7 on 2024-05-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_manager', '0004_remove_testinstance_subjects_testinstance_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('test_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_manager.testinstance')),
            ],
        ),
    ]
