# Generated by Django 4.2.7 on 2024-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_manager', '0007_alter_useranswer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='total_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
