# Generated by Django 4.2.7 on 2024-05-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_alter_questions_answer'),
        ('quiz_manager', '0010_alter_userscore_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.year'),
        ),
    ]
