# Generated by Django 4.2.7 on 2024-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_manager', '0012_totalstudytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalstudytime',
            name='Overall_study_time',
        ),
        migrations.AddField(
            model_name='totalstudytime',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='totalstudytime',
            name='overall_study_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
