# Generated by Django 4.2.7 on 2024-06-04 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_manager', '0014_alter_totalstudytime_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
