# Generated by Django 4.2.13 on 2024-07-20 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_manager', '0021_userscore_date_userdailyoveralscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserDailyOveralScore',
        ),
    ]
