# Generated by Django 4.2.13 on 2024-07-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_manager', '0022_userscore_user_delete_userdailyoveralscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.AlterField(
            model_name='userscore',
            name='test_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='quiz_manager.testinstance'),
        ),
    ]
