# Generated by Django 4.2.7 on 2023-12-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_uploader',
            field=models.BooleanField(default=False),
        ),
    ]
